# Generated by Django 3.1.2 on 2020-10-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customgroup',
            options={'ordering': ['name'], 'verbose_name': 'Gruppe', 'verbose_name_plural': 'Gruppen'},
        ),
    ]
